name: GitHub Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]  # Runs daily
  workflow_dispatch:                # Manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg  
          token: ${{ secrets.METRICS_TOKEN }}
          user: Deepakk200
          base: ""
          config_timezone: Asia/Kolkata

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year  
