name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at 12 AM UTC
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_METRICS_TOKEN }}
          user: Deepakk200
          filename: metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Calcutta

          # Plugins
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_ignored: html
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 8

          plugin_contributors: yes
          plugin_lines: yes
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: 0
